yamax:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
    
  neck_position_controller:
    type: position_controllers/JointPositionController
    joint: neck

  shoulder_right_x_position_controller:
    type: position_controllers/JointPositionController
    joint: shoulder_right_x

  shoulder_right_z_position_controller:
    type: position_controllers/JointPositionController
    joint: shoulder_right_z

  shoulder_left_x_position_controller:
    type: position_controllers/JointPositionController
    joint: shoulder_left_x

  shoulder_left_z_position_controller:
    type: position_controllers/JointPositionController
    joint: shoulder_left_z

  elbow_right_position_controller:
    type: position_controllers/JointPositionController
    joint: elbow_right

  elbow_left_position_controller:
    type: position_controllers/JointPositionController
    joint: elbow_left

  backbone_1_position_controller:
    type: position_controllers/JointPositionController
    joint: backbone_1

  backbone_2_position_controller:
    type: position_controllers/JointPositionController
    joint: backbone_2

  hip_joint_right_z_position_controller:
    type: position_controllers/JointPositionController
    joint: hip_joint_right_z

  hip_joint_right_x_position_controller:
    type: position_controllers/JointPositionController
    joint: hip_joint_right_x

  hip_joint_left_z_position_controller:
    type: position_controllers/JointPositionController
    joint: hip_joint_left_z

  hip_joint_left_x_position_controller:
    type: position_controllers/JointPositionController
    joint: hip_joint_left_x

  knee_right_position_controller:
    type: position_controllers/JointPositionController
    joint: knee_right

  knee_left_position_controller:
    type: position_controllers/JointPositionController
    joint: knee_left

  ankle_1_right_position_controller:
    type: position_controllers/JointPositionController
    joint: ankle_1_right

  ankle_1_left_position_controller:
    type: position_controllers/JointPositionController
    joint: ankle_1_left

  ankle_2_right_position_controller:
    type: position_controllers/JointPositionController
    joint: ankle_2_right

  ankle_2_left_position_controller:
    type: position_controllers/JointPositionController
    joint: ankle_2_left
